export const TICKET_TYPE_PAYMENTS = "PAYMENTS";
export const TICKET_TYPE_SOFTWARE = "SOFTWARE_ISSUES";
export const TICKET_TYPE_SHOP = "SHOP_ISSUES";
export const TICKET_TYPE_HELP = "HELP_NEEDED";
export const AVAILABLE_TICKET_TYPES = [TICKET_TYPE_PAYMENTS, TICKET_TYPE_SOFTWARE, TICKET_TYPE_SHOP, TICKET_TYPE_HELP];