export const CREATE_TICKET_ACTION = "CREATE_TICKET" ;
export const CREATE_PAYMENTS_TICKET = "CREATE_PAYMENTS_TICKET" ;

export const FETCH_TICKET_ACTION = "FETCH_TICKET";
export const UPDATE_TICKETS_MASSIVE_ACTION = "UPDATE_TICKETS_MASSIVE";

export const TICKET_TABLE_ACTION = "TICKET_TABLE";
export const FILTER_TABLE_ACTION = "FILTER_TABLE";
