export const CREATE_TICKET_ACTION = "CREATE_TICKET" ;
export const CREATE_PAYMENT_TICKET_ACTION = "CREATE_PAYMENT_TICKET" ;
export const CREATE_PAYMENT_TICKET_DEMO_ACTION = "CREATE_PAYMENTS_TICKET_DEMO" ;

export const FETCH_TICKETS_ACTION = "FETCH_TICKETS";
export const REORDER_TICKETS_ACTION = "REORDER_TICKETS";
export const UPDATE_TICKET_ACTION = "UPDATE_TICKET";

export const TICKET_TABLE_ACTION = "TICKET_TABLE";
export const FILTER_TABLE_ACTION = "FILTER_TABLE";
