export const CREATE_TICKET_ACTION = "CREATE_TICKET" ;
export const CREATE_PAYMENTS_TICKET = "CREATE_PAYMENTS_TICKET" ;

export const FETCH_TICKET_ACTION = "FETCH_TICKET";
export const UPDATE_TICKETS_MASSIVE_ACTION = "UPDATE_TICKETS_MASSIVE";

export const UPDATE_TICKET_ACTION = "UPDATE_TICKET";
export const UPDATE_PAYMENTS_TICKET = "UPDATE_PAYMENTS_TICKET";
export const UPDATE_SOFTWARE_TICKET = "UPDATE_SOFTWARE_TICKET";

export const ADD_TICKET_DETAILS_COMMENT = "ADD_TICKET_DETAILS_COMMENT";
export const EDIT_TICKET_DETAILS_VALUE = "EDIT_TICKET_DETAILS_VALUE";

export const TICKET_TABLE_ACTION = "TICKET_TABLE";
export const FILTER_TABLE_ACTION = "FILTER_TABLE";
