export const TICKET_TYPE_PAYMENTS = "PAYMENTS";
export const TICKET_TYPE_SOFTWARE = "SOFTWARE_ISSUES";

export const TICKET_PRIORITY_HIGH = "High";
export const TICKET_PRIORITY_MEDIUM= "Medium";
export const TICKET_PRIORITY_LOW= "Low";

export const TICKET_STATUS_OPEN= "Open";
export const TICKET_STATUS_CLOSED= "Closed";

export const AVAILABLE_TICKET_TYPES = [TICKET_TYPE_PAYMENTS];
export const AVAILABLE_TICKET_PRIORITY_TYPES = [TICKET_PRIORITY_HIGH, TICKET_PRIORITY_MEDIUM, TICKET_PRIORITY_LOW];
export const AVAILABLE_TICKET_STATUS_TYPES = [TICKET_STATUS_OPEN, TICKET_STATUS_CLOSED];