export const TICKET_DETAILS_ACTION = "TICKET_DETAILS";
export const TICKET_DETAILS_CREATE_COMMENT_ACTION = "TICKET_DETAILS_CREATE_COMMENT";
export const FETCH_TICKET_DETAILS_ACTION = "FETCH_TICKET_DETAILS";